---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
data:
  db: {{ .Values.secret.db | b64enc }}
  postgres_password: {{ .Values.env.postgresPassword | b64enc }}
